import type { VideoFactoryProviderDefinition } from './video-factory.types'

export const VIDEO_FACTORY_PROVIDERS: readonly VideoFactoryProviderDefinition[] = [
  {
    id: 'public-web-research',
    label: 'Public Web Research',
    capability: 'research',
    costTier: 'free',
    priority: 10,
    enabledByDefault: true,
  },
  {
    id: 'local-llm-script',
    label: 'Local LLM Script',
    capability: 'script',
    costTier: 'local',
    priority: 10,
    enabledByDefault: true,
    requiredEnv: 'VIDEO_FACTORY_LOCAL_LLM_ENDPOINT',
    setupHint: 'Point VIDEO_FACTORY_LOCAL_LLM_ENDPOINT at an Ollama/OpenAI-compatible local endpoint.',
  },
  {
    id: 'public-domain-assets',
    label: 'Public-domain / licensed assets',
    capability: 'assets',
    costTier: 'free',
    priority: 10,
    enabledByDefault: true,
  },
  {
    id: 'piper-local',
    label: 'Piper TTS (local)',
    capability: 'voice',
    costTier: 'local',
    priority: 10,
    enabledByDefault: true,
    requiredEnv: 'VIDEO_FACTORY_PIPER_PATH',
    setupHint: 'Set VIDEO_FACTORY_PIPER_PATH to the Piper executable.',
  },
  {
    id: 'local-video-model',
    label: 'Local video model adapter',
    capability: 'video-generation',
    costTier: 'local',
    priority: 10,
    enabledByDefault: true,
    requiredEnv: 'VIDEO_FACTORY_LOCAL_VIDEO_ENDPOINT',
    setupHint: 'Point VIDEO_FACTORY_LOCAL_VIDEO_ENDPOINT at a local WAN/LTX/Hunyuan/CogVideo-compatible adapter.',
  },
  {
    id: 'aitoearn-native-video',
    label: 'AiToEarn native video providers',
    capability: 'video-generation',
    costTier: 'paid',
    priority: 100,
    enabledByDefault: true,
    setupHint: 'Uses the existing AiToEarn cloud video provider layer and is eligible only when paid providers are explicitly allowed.',
  },
  {
    id: 'ffmpeg-local',
    label: 'FFmpeg (local)',
    capability: 'compose',
    costTier: 'local',
    priority: 10,
    enabledByDefault: true,
    requiredEnv: 'VIDEO_FACTORY_FFMPEG_PATH',
    setupHint: 'Set VIDEO_FACTORY_FFMPEG_PATH to the FFmpeg executable.',
  },
  {
    id: 'local-llm-qa',
    label: 'Local LLM QA',
    capability: 'qa',
    costTier: 'local',
    priority: 10,
    enabledByDefault: true,
    requiredEnv: 'VIDEO_FACTORY_LOCAL_LLM_ENDPOINT',
    setupHint: 'Uses the same local LLM endpoint as script generation.',
  },
  {
    id: 'ffmpeg-export',
    label: 'FFmpeg export',
    capability: 'export',
    costTier: 'local',
    priority: 10,
    enabledByDefault: true,
    requiredEnv: 'VIDEO_FACTORY_FFMPEG_PATH',
    setupHint: 'Set VIDEO_FACTORY_FFMPEG_PATH to the FFmpeg executable.',
  },
] as const
