import type { VideoFactoryProviderDefinition } from './video-factory.types'

export const VIDEO_FACTORY_PROVIDERS: readonly VideoFactoryProviderDefinition[] = [
  {
    id: 'aitoearn-ai-script',
    label: 'AiToEarn AI Script',
    capability: 'script',
    costTier: 'free',
    priority: 10,
    enabledByDefault: true,
  },
  {
    id: 'public-web-research',
    label: 'Public Web Research',
    capability: 'research',
    costTier: 'free',
    priority: 10,
    enabledByDefault: true,
  },
  {
    id: 'public-domain-assets',
    label: 'Public-domain / licensed assets',
    capability: 'assets',
    costTier: 'free',
    priority: 10,
    enabledByDefault: true,
  },
  {
    id: 'piper-local',
    label: 'Piper TTS (local)',
    capability: 'voice',
    costTier: 'local',
    priority: 10,
    enabledByDefault: true,
    setupHint: 'Install Piper and expose its executable to the runtime.',
  },
  {
    id: 'local-video-model',
    label: 'Local video model adapter',
    capability: 'video-generation',
    costTier: 'local',
    priority: 10,
    enabledByDefault: true,
    setupHint: 'Connect a local WAN/LTX/Hunyuan/CogVideo-compatible adapter when GPU capacity is available.',
  },
  {
    id: 'aitoearn-native-video',
    label: 'AiToEarn native video providers',
    capability: 'video-generation',
    costTier: 'paid',
    priority: 100,
    enabledByDefault: true,
    setupHint: 'Uses the existing AiToEarn cloud video provider layer and is only eligible when paid providers are explicitly allowed.',
  },
  {
    id: 'ffmpeg-local',
    label: 'FFmpeg (local)',
    capability: 'compose',
    costTier: 'local',
    priority: 10,
    enabledByDefault: true,
    setupHint: 'Install FFmpeg and expose its executable to the runtime.',
  },
  {
    id: 'aitoearn-ai-qa',
    label: 'AiToEarn AI QA',
    capability: 'qa',
    costTier: 'free',
    priority: 10,
    enabledByDefault: true,
  },
  {
    id: 'ffmpeg-export',
    label: 'FFmpeg export',
    capability: 'export',
    costTier: 'local',
    priority: 10,
    enabledByDefault: true,
    setupHint: 'Install FFmpeg and expose its executable to the runtime.',
  },
] as const
